# Change these first
owner: merakioffice # Your GitHub organization or username, where this repository lives
repo: mensores-status # The name of this repository

sites:
  - name: "[PROD] Globalfinder"
    url: "https://globalfinder.com.ar"
  - name: "[QA] Pmsubeescaleras"
    url: "https://qa.pmsubeescaleras.com.ar"
  - name: "[QA] IF-Colombia"
    url: "https://qa.ifc.mensorestudio.com"
  - name: "[QA] Mensorestudio"
    url: "https://qa2.mensorestudio.com"
  - name: "[QA] Mensorestudio ARG"
    url: "https://qa2.mensorestudio.com.ar"
  - name: "[QA] Ortopedia Suiza"
    url: "https://qa.ortopediasuiza.com.ar/"
  - name: "[PROD] Hidalgo & Asociados"
    url: "https://hidalgoyasociados.com.ar/"
  - name: "capaccioli"
    url: "https://qa.capaccioli.mensorestudio.com/"
  - name: "Ecosud"
    url: "https://qa.ecosud.mensorestudio.com.ar/"
  - name: "Decoacuarios"
    url: "https://qa.decoacuarios.com.ar/"   
    
assignees: # Users to assign downtime issues (optional)
  - merakioffice
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /mensores-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: /mensores-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
